reg/urls.py
from django.urls import path

from . import views

app_name = 'reg'
urlpatterns = [
    path('', views.home, name='home'),
    path('create_st/', views.create_st, name='create_st'),
    # path('groups/', views.groups, name='groups'),
    # path('detail/<int:groupss_id>',views.detail, name='detail'),
    
    # path('updategroup/<str:pk>',views.updategroup, name='updategroup'),
    # path('delete/<str:pk>',views.deletegroup, name='deletegroup'),
    # path('group_csv/',views.group_csv, name='group_csv'),
    # path('group_csv_m/',views.group_csv_m, name='group_csv_m'),
]

registration/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reg.urls'))
]

reg/models.py
from django.db import models

# Create your models here.
class Students(models.Model):
    name = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    phno = models.CharField(max_length=10)
    clg_name = models.CharField(max_length=30)
    corse_name = models.CharField(max_length=10)

reg/views.py
from django.shortcuts import render,redirect
from reg.form import Student_creation_form
# Create your views here.


def home(request):
    return render(request, 'reg/home.html')



def create_st(request):
    form = Student_creation_form()
    if request.method == 'POST':
        form = Student_creation_form(request.POST)
        if form.is_valid(): 
            form.save()
            return redirect('/')
    context = {'form':form}
    return render(request,'reg/stud_creation_form.html', context)



# def group_csv(requst):
#     response=HttpResponse(content_type ='text/csv')
#     response['Content-Disposition']= 'attachmet; filename=venuev.csv'
#     # create a csv writer
#     writer = csv.writer(response)
#     # desain the model
#     group = Groupss.objects.all()

#     # add column headings to the csv file
#     writer.writerow(['Group_name', 'Member1', 'Member2', 'Email M1','Email M2', 'Ph No M1', 'Ph No M2'])
#     for team in group:
#         writer.writerow([team.g_name, team.cn1, team.cn2, team.cn1em, team.cn2em, team.cn1ph, team.cn2ph, team.clg_name])
#     return response

# def group_csv_m(request):
#     response=HttpResponse(content_type ='text/csv')
#     response['content-disposition']='attachmet; filename=members.csv'

#     writer = csv.writer(response)

#     group = Groupss.objects.all()

#     writer.writerow(['Name','colleg','phone number', 'Emal'])
#     for team in group:
#         writer.writerow([team.cn1, team.clg_name, team.cn1ph, team.cn1em])
#         writer.writerow([team.cn2, team.clg_name, team.cn2ph, team.cn2em])
#     return response 


# def groups(request):
#     ls = Groupss.objects.all().order_by('-id')
    
#     filter = GroupFilter(request.GET,queryset=ls)
#     ls = filter.qs
#     context = {'ls' : ls,
#         'filter':filter    
#     }
#     return render(request, 'regi/full_lst.html',context)

# def detail(request,groupss_id):
#     # from django.shortcuts import get_object_or_404, render
#     # question = get_object_or_404(Question, pk=question_id)
#     try:
#         it = Groupss.objects.get(pk=groupss_id)
#     except:
#         raise Http404("Group does not exist")
#     return render(request,'regi/detail.html', {'it': it})
    
# 

# def updategroup(request,pk):
#     group = Groupss.objects.get(id=pk)
#     form = GroupForm(instance=group)

#     if request.method == 'POST':
#         form = GroupForm(request.POST,instance=group)
#         if form.is_valid():
#             form.save()
#             return redirect('/')
#     context = {'form':form}
#     return render(request,'regi/gp_c_form.html', context)


# def deletegroup(request,pk):
#     group = Groupss.objects.get(id=pk)
#     if request.method =='POST':
#         group.delete()
#         return redirect('/')
#     context = {'group':group}
#     return render(request,'regi/delete.html',context)

reg/templates/reg/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>S-Group</title>

        <!-- Bootstrap CSS CDN -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <!-- Our Custom CSS -->
        <link rel="stylesheet" href="{% static 'regi/h/style2.css' %}">
        <!-- Scrollbar Custom CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    </head>
    <body id="intro">

        <div class="wrapper">
            <!-- Sidebar Holder -->
            <nav id="sidebar">
                <!-- <div class="sidebar-header">
                    <ul class="list-unstyled components">
                        <li class="active">
                            <h3>MES AIMAT</h3>
                        </li>
                    </ul>
                </div> -->

                <ul class="list-unstyled components">
                    <li class="active">
                        <a href="{#% url 'regi:index' %}">
                            <h3>MES AIMAT</h3>
                        </a>
                    </li>
                    <br>
                    <li class="">
                        <a href="{% url 'reg:home' %}">Home</a>
                    </li>
                    <br>
                    <li class="">
                        <a href="{% url 'reg:create_st' %}">New Group<h3>+</h4></a>
                    </li>   
                    <li class="">
                        <a href="{#% url 'regi:groups' %}">Groups Search</a>
                    </li>
                    <br><br><br><br><br>
                    <li class="">
                        <a href="{#% url 'regi:group_csv' %}">Excel Export</a>
                    </li>
                    <li class="">
                        <a href="{#% url 'regi:group_csv_m' %}">Excel M Export</a>
                    </li>
                </ul>

            </nav>
        </div>
            <!-- Page Content Holder -->
            <div id="content">

                <nav class="navbar navbar-default">
                    <div class="container-fluid">

                        <div class="navbar-header">
                            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                                <i class="glyphicon glyphicon-align-left"></i>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="#">Page</a></li>
                            </ul>
                        </div>
                    </div>
                </nav>

                <div class="stile1">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
          
            
        <!-- jQuery CDN -->
        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <!-- Bootstrap Js CDN -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <!-- jQuery Custom Scroller CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

        <script type="text/javascript">
            $(document).ready(function () {
                $("#sidebar").mCustomScrollbar({
                    theme: "minimal"
                });

                $('#sidebarCollapse').on('click', function () {
                    $('#sidebar, #content').toggleClass('active');
                    $('.collapse.in').toggleClass('in');
                    $('a[aria-expanded=true]').attr('aria-expanded', 'false');
                });
            });
        </script>
    </body>
</html>

reg/templates/reg/home.html
{% extends "reg/base.html" %}
{% block content %}

    <h1 class="ud">Group List</h1>
    
{% endblock content %}

reg/templates/reg/stud_creation_form.html
{% extends "reg/base.html" %}
{% load static %}
{% block content %}

<h3 class="ud">Edit groups</h3>
<form method="POST">
    {%csrf_token%}
    <div class="form-row">
        <div class="name">name</div>
        <div class="input--style-6 value">
            {{form.name}}
        </div>
    </div>
    <div class="form-row">
        <div class="name">Email</div>
        <div class="input--style-6 value">
            {{form.email}}
        </div>
    </div>

    <div class="form-row">
        <div class="name">phone no</div>
        <div class="input--style-6 value">
            {{form.phno}}
        </div>
    </div>
    
    <div class="form-row">
        <div class="name">clg_name</div>
        <div class="input--style-6 value">
            {{form.clg_name}}
        </div>
    </div>
    <div class="form-row">
        <div class="name">course_sem</div>
        <div class="input--style-6 value">
            {{form.corse_name}}
        </div>
    </div>
    <br>
    
    <div>
        <input class="button primary" type="submit" value="save">   
</form>
{{form.errors}}

{% endblock content %}